name: network_logger
description: Network logger with well designed user interface to inspect network traffic logs. Included with Dio interceptor.
version: 1.0.3
homepage: https://github.com/themisir/flutter-network-logger

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dio: ^5.4.0
  intl: ^0.18.1
  flutter_json_viewer: ^1.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
