name: network_logger
description: Network logger with well designed user interface to inspect network traffic logs. Included with Dio interceptor.
version: 1.0.3
homepage: https://github.com/themisir/flutter-network-logger

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dio: ^4.0.0
  intl: ^0.17.0
  flutter_json_viewer: ^1.0.1
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  open_filex: ^4.3.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
